### ISSUE TITLE
A12 support?

### ISSUE THREAD

**Issue by Macleykun** [jacc/wiivamp#1]
Hi!
I enjoy using your tweak on my iPad and the recent chimera jailbreak allowed me to also put your tweak on my A12 device.

I was wondering if you would be interested/able to also support A12.
Hope to hear from you soon!

**Comment by jacc** [comment]
The repo has been updated with arm64e support and an update was just pushed to Dynastic with A12 support. Enjoy!

**Comment by Macleykun** [comment]
Hey Jacc!
Thank for updating Wiivamp for A12(X) devices! The tweak seems to be working fine! Thank you so much and have a great weekend!

**Comment by jacc** [comment]
Enjoy :)
