### ISSUE TITLE
appstore crash

### ISSUE THREAD

**Issue by eliekh05** [jacc/wiivamp#13]
after i installed the wiivamp from dynastic repo and i went to open appstore it will open for like 5 minutes and crash can you fix it

Device: A1566
iOS: 15.8.2
Jailbreak: Palera1n Rootful

@jacc @Diatrus

**Comment by jacc** [comment]
saw your email and double pinging me on a different platform isn't going to change the fact that wiivamp is half a decade old. i left the jailbreak community for a damn good reason and absolutely will not be updating this
